### ISSUE TITLE
软件中心“选择操作”下拉框的建议

### ISSUE THREAD

**Issue by king32783784** [isoft-linux/isoftapp#15]
软件中心“选择操作”下拉框臃肿，点击“选择操作”下拉框出现“打开、软件卸载、升级、选择操作“出现４个选项。
其实，下拉框只实现了３个功能“打开、卸载、更新”，但现在有４个选项，多了一个“选择操作”，“选择操作”选项的作用类似于复位的功能。
　
建议修改这部分的设计，现在选中下拉框中的某一个选项，其实是实现了两个动作选中和执行，可以将两个部分拆分，这样下拉框只显示“打开、更新、卸载”，动作变为选中对应选项后对应选项变为默认，并且按钮变蓝，再次点击，对应选项执行。
   　或则放弃下拉框的设计，选择其他方式呈现功能按钮。或则只保留安装和已安装状态。

**Comment by xiangzhai** [comment]
ping PM...

**Comment by xiangzhai** [comment]
fixed https://github.com/isoft-linux/isoftapp/commit/7727a7f21d7ea976367938ec8eec5dce785d34de
